# Generated by Django 3.2 on 2021-04-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnombre', models.CharField(blank=True, max_length=64, null=True)),
                ('chnivel', models.CharField(choices=[('BA', 'Basico'), ('IN', 'Intermedio'), ('AV', 'Avanzado'), ('FL', 'Fluido')], default='BA', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chabilidadesRequeridas', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chescolaridad', models.CharField(choices=[('PR', 'Primaria'), ('SC', 'Secundaria'), ('PP', 'Preparatoria'), ('UV', 'Universidad'), ('MA', 'Maestria')], default='PR', max_length=2)),
                ('iexperiencia', models.IntegerField()),
                ('fsalario', models.FloatField()),
                ('chabilidadesRequeridas', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('iidioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posiciones.idioma')),
                ('itipoDePuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posiciones.tipodepuesto')),
            ],
        ),
    ]
