# Generated by Django 3.2 on 2021-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='cnombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
