# Generated by Django 3.2 on 2021-04-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0002_alter_idioma_cnombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodepuesto',
            name='chabilidadesRequeridas',
        ),
        migrations.AddField(
            model_name='tipodepuesto',
            name='cnombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
