# Generated by Django 3.2 on 2021-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0003_auto_20210430_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idioma',
            name='cnombre',
        ),
        migrations.AddField(
            model_name='idioma',
            name='chidioma',
            field=models.CharField(choices=[('IN', 'Ingles')], default='IN', max_length=2),
        ),
    ]
