# Generated by Django 3.2 on 2021-05-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posiciones', '0004_auto_20210503_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnombre', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='posicion',
            name='icategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posiciones.categoria'),
        ),
    ]
