# Generated by Django 3.2 on 2021-04-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnombre', models.TextField()),
                ('cdireccion', models.TextField()),
                ('itelefono', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
