# Generated by Django 3.2 on 2021-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_cnombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='itelefono',
            field=models.IntegerField(default=0),
        ),
    ]
