# Generated by Django 3.2 on 2021-04-30 19:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_itelefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='itelefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
