# Generated by Django 3.2 on 2021-04-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_empresa_itelefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='itelefono',
            field=models.CharField(max_length=30),
        ),
    ]
